##
#  @file
#  Configuration file for specifying project requirement and metadata.
#
#  @copyright
#  Copyright (c) 2023, Codevience. All rights reserved.<BR>
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
#
#  @par reference
#  - https://pip.pypa.io/
#
##
